apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-shell-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-shell-app
  template:
    metadata:
      labels:
        app: spring-shell-app
    spec:
      containers:
        - name: spring-shell-app
          image: nikhithagurunatham/spring-shell-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/springboot
---
apiVersion: v1
kind: Service
metadata:
  name: spring-shell-service
spec:
  type: NodePort
  selector:
    app: spring-shell-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
